# Generated by Django 4.2.14 on 2024-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
